language: rust
sudo: false
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
rust:
  - 1.18.0
  - stable
  - beta
  - nightly
before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
services:
  - redis-server
script:
  - |
      travis-cargo build &&
      travis-cargo test &&
      travis-cargo bench &&
      travis-cargo --only stable doc
after_success:
  - travis-cargo --only stable doc-upload
env:
  global:
    - secure: Ss/dJ+hq4i0k72mntBSHkvSvNgyfL1/quVxdc9p8zXpT/7OXvEFf4wqeLBmP/kJvyn7I2qPOME6D2FxmNrw/jrosQ7OSgjw85ohzUXOST6+hn+N18Q3juWy3SlWxiWa7UpaAFP+VJjvuYeWC0tu7+N8v5JR3uMy0MIHW+FZWzicXnF7ANy4Lj9vW7pkQPUXKUI5hSU7/kNdPlFfecxqTGJifBxLLseeB6o6Wi5G/OxS2jTWVRcr9ztRIGM8odoU7HAvWqIu/HEQu/c5/q7MfwIXUnYsUYxNBDvr+cQHiTfIqeA+9mMMlKCPxHTVOBvmX4GXKX3BF1dTfkt2kRxYD1wttQVH+WgXHLRxlEsWB7H6v9r8FgYb2mIOi9c51X5uH2/5FMPNYIOVuy/mqmi0PX0sP9nbwpFUIvg8H3rwL9/y+meKUrsdntdSHHa+WkGNj+hXdTv/JWPefvHZivFU+/nr9rtH+AXhbU9MsgAqAPzB7bt1P2tnvQ3wnmay0hRqcW4g2aF1+q+1jT0m1ubQGeDgF20BC/YW66MjeGaGQwzm68LHc9b5dcQE+OuDB00JyPUqsqG3gVQwIPsjr/xWiZh//g0YTaqjMa/1yVu2qd8fHfSkENYXDRlX2SPXU5YAuzohJNDVPi9XU/Gkod8IhYJ5JzaLezy4twesh/Okqltk=
    - TRAVIS_CARGO_NIGHTLY_FEATURE: ''
    - RUST_BACKTRACE: 1
