[package]
name = "spaceapi-server"
version = "0.4.0"
documentation = "https://coredump-ch.github.io/spaceapi-server-rs/"
repository = "https://github.com/coredump-ch/spaceapi-server-rs"
license = "MIT OR Apache-2.0"
authors = [
    "Raphael Nestler <raphael.nestler@gmail.com>",
    "Danilo Bargen <mail@dbrgn.ch>",
    "Stefan Schindler <stefan@estada.ch>",
]
description = "A library that allows you to easily implement a Space API server."
readme = "README.md"
keywords = ["spaceapi", "hackerspaces", "status", "api", "server"]
include = [
    "**/*.rs",
    "Cargo.toml",
    "README.md",
    "CHANGELOG.md",
    "AUTHORS.md",
    "LICENSE-MIT",
    "LICENSE-APACHE",
]

[badges]
travis-ci = { repository = "coredump-ch/spaceapi-server-rs" }

[dependencies]
r2d2 = "^0.7"
r2d2_redis = "^0.6"
redis = "^0.8"
rustc-serialize = "^0.3"
log = "^0.4"
iron = "^0.5"
urlencoded = "^0.5"
router = "^0.5"
error-type = "^0.1"
serde_json = "^1.0"
spaceapi = "^0.5.0"
clippy = {version = "^0.0", optional = true}

[features]
unstable = ["clippy"]

[dev-dependencies]
env_logger = "^0.5"
